### PR TITLE
Updated target and base version references

### PR DESCRIPTION
**Pull request by BenHesketh21**
#466

### CODE REVIEW

**Comment by BenHesketh21** [comment]
This is my solution to issue #466 but I can't seem to link the issue

**Comment by BenHesketh21** [comment]
closes #466

**Comment by GalmWing** [comment]
I hit this same issue, any chance you guys can merge this in? It's been a couple of months of inactivity
@bryanmacfarlane, @scottdallamura

**Comment by ASaiAnudeep** [comment]
@BenHesketh21 why this PR not merged into the master branch?

**Comment by BenHesketh21** [comment]
I made another PR but no one has looked at either #511

**Pull request closed without merging**
