### PR TITLE
Allow cross domain authorization by default and add unit tests

### PR DESCRIPTION
**Pull request by EzzhevNikita**
In this PR we are changing default value of allowCrossOriginAuthentication parameter for authorization handlers to true. When this parameter was introduced in typed-rest-client it becomes breaking change for the tasks that is using azure-devops-node-api it started causing authorization issues on redirects, since there are some cases when requests is processing with redirects). We could trust such redirects since they are initiated by Azure DevOps server. So to prevent future issues with upgrading azure-devops-node-api in tasks we are allowing cross origin authorization by default. 

Also by this PR was added units that checks that authorization handlers is initializing with right value for the allowCrossOriginAuthentication parameter

UPD: One small improvement, looks like it was mistake in wildcard in .gitignore for tests folder and js files in subfolders weren't excluded from committing. Wildcard fixed and tests.js was removed.

### CODE REVIEW

**Review by damccorm — APPROVED** [review]
Could you bump the version in the package.json as well please?

**Comment by EzzhevNikita** [comment]
> Could you bump the version in the package.json as well please?

Sure, done!

**Review by DaniilShmelev — APPROVED** [review]
Judging by [this line](https://github.com/microsoft/azure-devops-node-api/blob/b128655582769494491c13598c1ab930665f64c4/.gitignore#L9), .js files in tests shouldn't be committed. Could you please fix this? Otherwise LGTM

**Review by anatolybolshakov — APPROVED** [review]
LGTM, thanks! Please add also some notes about removed tests.js in description.

**Pull request merged**
