### PR TITLE
Updated PAT length

### PR DESCRIPTION
**Pull request by jankolarikMSFT**
We have updated the PAT format and the length has changed from 52 characters to 84 characters: https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=Windows#changes-to-format

Before the rollout is fully complete and to prepare for the transition period between the new and old PAT formats, I would like to adjust this library to work with both of these formats/lengths.

### CODE REVIEW

**Review by DergachevE — APPROVED** [review]

**Comment by jankolarikMSFT** [comment]
Merged #608

**Pull request closed without merging**
