### PR TITLE
Enable retries

### LINKED ISSUE #292: Intermittent ECONNRESET errors
### Environment

Node version: 11.12
Npm version: 6.2
OS and version: Windows 2018 server (Azure DevOps release pipelines)
azure-devops-node-api version: 7.0.0 (also 6.x)

### Issue Description

I'm experiencing intermittent [ECONNRESET](https://stackoverflow.com/questions/17245881/node-js-econnreset) errors [running](https://github.com/dmitryserbin/azdev-release-orchestrator) various Build/Core/Release API methods against Azure DevOps projects or pipelines. Failure rate is about 1-2 per 100 calls.

The issue affects various APIs, for example:

- IReleaseApi > getRelease, getReleases, getReleaseDefinition, etc.
- IBuildApi > getBuild, getBuilds, getBuildTags, etc.
- ICoreApi > getProject

Basically, I'm forced to use a retry mechanism on top of the methods as a workaround:

```typescript
        let result: Build | undefined;
        let retryAttempt: number = 0;

        while (retryAttempt < retry) {
            try {
                retryAttempt++;
                // Get build
                result = await this.buildApi.getBuild(buildId, projectName);
                // Stop retrying on success
                retryAttempt = retry;
            } catch {
                console.log(`Retry retrieving build..`);
                // Delay before next retry
                await this.delay(timeout);
            }
        }
```

I do not believe there's anything wrong with your code, but please advise if it's possible to address these type of issues on the library level? For example, by introducing a native retry mechanism (or anything else you could recommend).

### Expected behaviour

API should return response.

### Actual behaviour

ECONNRESET thrown.

### Steps to reproduce

It is challenging to reproduce as you need need to be very lucky. The task I'm running in a pipeline is making >100 call per ~5 min. I have never experienced this issue locally - it only happens in Azure DevOps pipelines.

### Logs

Not much logs at this point, but I can get some, if needed.

```
2019-03-16T16:06:07.4473715Z ##[error]read ECONNRESET
```

### PR DESCRIPTION
**Pull request by damccorm**
Fixes #292

### CODE REVIEW

**Comment by antmeehan** [comment]
Great stuff! When does this land in a release?

**Comment by dmitryserbin** [comment]
Hey @damccorm @stephenmichaelf when are you guys planning to release this to the [npm](https://www.npmjs.com/package/azure-devops-node-api) repo?

**Comment by stephenmichaelf** [comment]
@bryanmacfarlane Can we publish?

**Comment by damccorm** [comment]
Sorry for the delay, this should be published now.

**Comment by damccorm** [comment]
@antmeehan @dmitryserbin FYI

**Pull request merged**
