### PR TITLE
Fixed issue with serialization

### PR DESCRIPTION
**Pull request by damccorm**
Fixes issue where key would appear twice in serialized string (e.g. key=key=value instead of key=value).

Addresses #215

### CODE REVIEW

**Comment by stephenmichaelf** [comment]
Thanks, can you bump the patch version?

**Comment by stephenmichaelf** [comment]
Thanks! Appreciate the fast turn around.

@bryanmacfarlane Can we release this today?

**Comment by stephenmichaelf** [comment]
@damccorm Let's make an Issue to track adding the L0/L1 tests.

**Comment by damccorm** [comment]
@stephenmichaelf Added #217 to track it

**Pull request merged**
